name: inline_result
description: This package brings a Kotlin-like Result<T> to Dart, using extension types for zero-cost wrapping.
version: 1.0.0
repository: https://github.com/Vorkytaka/inline_result

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
