name: inline_result
description: This package brings a Kotlin-like Result<T> to Dart, using extension types for zero-cost wrapping.
version: 1.1.0
repository: https://github.com/Vorkytaka/inline_result
issue_tracker: https://github.com/Vorkytaka/inline_result/issues
topics:
  - result
  - inline
  - either
  - errors

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.0.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^4.0.0
  test: ^1.24.0
